theme = "dark_plus"

[editor]
line-number = "relative"
mouse = true
auto-save = true
scrolloff = 8
auto-format = true
bufferline = "always"
rulers = [80]
shell = ["zsh", "-c"]
true-color = true
auto-completion = true
cursorline = false
color-modes = true
idle-timeout = 40
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
# C-p = "file_picker"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
trail = "·"
nbsp = "⍽"
tab = "→"
newline = " "

[editor.indent-guides]
render = true
character = "│"

[editor.soft-wrap]
enable = false

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
separator = "│"
left = [
    "mode",
    "version-control",
    "spacer",
    "file-name",
    "file-modification-indicator",
]
right = [
    "spinner",
    "diagnostics",
    "file-type",
    "file-encoding",
    "file-line-ending",
    "position",
]

[editor.file-picker]
hidden = false
