# Install alacritty terminal

- create:
    - ~/.config/alacritty/

- link:
    ~/.config/alacritty/:
      glob: true
      path: config/alacritty/*.yml

- shell:
    - [sudo apt install -y alacritty, "Installing package: alacritty"]
