# Install alacritty terminal

- create:
    - ~/.config/alacritty/

- link:
    ~/.config/alacritty/alacritty.yml: config/alacritty/alacritty.yml

- shell:
    - [sudo apt install -y alacritty, "Installing package: alacritty"]
