# bash: bash shell configuration

- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/.config/bash/
    - ~/.local/state/bash/

- clean:
    ~/.config/bash/:

- link:
    ~/.bashrc: config/bash/bashrc.bash
    ~/.bash_logout: config/bash/bash_logout.bash

    ~/.config/bash/:
      glob: true
      path: config/bash/*.bash
