- create:
    - ~/.config/bash
    - ~/.config/bash/bashrc.d

- link:
    ~/.bashrc: config/bash/bashrc
    ~/.bash_logout: config/bash/bash_logout
    ~/.config/bash/bashrc.d:
      path: config/bash/bashrc.d/
