- create:
    - ~/.config/bash
    - ~/.config/bash/bashrc.d

- link:
    ~/.bashrc: dotfiles/bash/bashrc
    ~/.bash_logout: dotfiles/bash/bash_logout
    ~/.config/bash/bashrc.d:
      path: dotfiles/bash/bashrc.d/
