# Bat: A cat(1) clone with wings.
# https://github.com/sharkdp/bat

- create:
    - ~/.config/bat/

- link:
    ~/.config/bat/config: config/bat/config

- shell:
    - [sudo sh -c "apt install -y bat", Install package; bat]
    - [
        sudo sh -c "ln -sf /usr/bin/batcat /usr/local/bin/bat",
        Create symbolic link for binary batcat -> bat,
      ]
