- sudo:
    - shell:
        - [apt update && apt install -y docker docker-compose]
        - [groupadd docker, Creating 'docker' group]
        - [gpasswd -a $USER docker, Add current user to 'docker' group]
