# fd-find | A simple, fast and user-friendly alternative to 'find'
# https://github.com/sharkdp/fd

- shell:
    - [sudo sh -c "apt install -y fd-find", Installing package; fd-find]
    - [
        sudo sh -c "ln -sf /usr/bin/fdfind /usr/local/bin/fd",
        Create symbolic link for binary fdfind -> fd,
      ]
