- defaults:
    shell:
      stderr: true
      stdout: true

- create:
    - ~/.local/share/fonts/

- shell:
    - [
        meta/scripts/install-nerdfonts.sh NerdFontsSymbolsOnly,
        "Installing fonts: NerdFonts",
      ]
    - [meta/scripts/install-monocraft.sh, "Installing fonts: Monocraft"]
