# Fzf: A command-line fuzzy finder
# https://github.com/junegunn/fzf

- defaults:
    link:
      force: true
    shell:
      stderr: true
      stdout: true

- create:
    - ~/.config/profile.d/

- clean:
    ~/.config/profile.d/:

- link:
    ~/.config/profile.d/fzf.sh: config/profile/profile.d/fzf.sh

- shell:
    - [meta/scripts/install-fzf.sh, "Running install script: fzf"]
