# Git: Version Control

- link:
    ~/.config/git/aliases: config/git/aliases
    ~/.config/git/config.local: config/git/config.local
    ~/.config/git/config: config/git/config
    ~/.config/git/ignore: config/git/ignore
    ~/.config/git/message: config/git/message

- shell:
    - [
        sudo sh -c "apt update && apt install -y git git-crypt git-lfs",
        "Installing packages: git, git-crypt, git-lfs",
      ]
