- create:
    - ~/.config/git

- link:
    ~/.config/git:
      glob: true
      force: true
      path: dotfiles/git/*

- sudo:
    - shell:
        - [apt update && apt install -y git git-fls, Install Git.]
