# Install kitty terminal

- create:
    - ~/.config/kitty

- link:
    ~/.config/kitty:
      glob: true
      path: config/kitty/*

- shell:
    - [sudo apt install -y kitty, Installing package; Kitty Terminal]
