# lazygit | simple terminal UI for git commands
# https://github.com/jesseduffield/lazygit

- create:
    - ~/.config/lazygit

- link:
    ~/.config/lazygit/config.yml:
      path: config/lazygit/config.yml

- shell:
    - [
        sh -c "sudo add-apt-repository ppa:lazygit-team/release",
        Add Package repository; lazygit-team,
      ]
    - [
        sudo apt update && sudo apt install -y lazygit",
        Installing Package; Lazygit,
      ]
