- link:
    ~/.local/bin:
      glob: true
      force: true
      path: dotfiles/local/bin/*

    ~/.local/lib:
      glob: true
      force: true
      path: dotfiles/local/lib/*

- shell:
    - [chmod +x dotfiles/local/bin/*]
