# ~/.local: Setup environment

- create:
    - ~/.local/bin/
    - ~/.local/lib/

- clean:
    ~/.local/bin:

- link:
    ~/.local/bin:
      force: true
      glob: true
      path: local/bin/*
    ~/.local/lib:
      force: true
      glob: true
      path: local/lib/*

- shell:
    - [
        sudo chmod 755 local/bin/*,
        Give '~/.local/bin/*' scripts executable privileges,
      ]
