# local: setup local xdg directories

- defaults:
    link:
      force: true
      glob: true
    shell:
      stderr: true
      stdout: true

- create:
    - ~/.local/bin/
    - ~/.local/lib/

- clean:
    ~/.local/bin/:
    ~/.local/lib/:

- link:
    ~/.local/bin: local/bin/*

- shell:
    - [
        sudo chmod +x local/bin/*,
        "Set executable privilege for all local/bin scripts.",
      ]
