# Macchina: Fast, minimal and customizable system information frontend.
# https://github.com/Macchina-CLI/macchina

- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- create:
    - ~/.config/macchina/
    - ~/.config/macchina/ascii/
    - ~/.config/macchina/themes/

- clean:
    ~/.config/macchina/:
      recursive: true

- link:
    ~/.config/macchina/macchina.toml: config/macchina/macchina.toml
    ~/.config/macchina/ascii/magneton.ascii: config/macchina/ascii/magneton.ascii
    ~/.config/macchina/themes/Neodymium.toml: config/macchina/themes/Neodymium.toml

- shell:
    - [cargo install macchina]
