# neovim | https://github.com/neovim/neovim
# Vim-fork focused on extensibility and usability.

- defaults:
    shell:
      stderr: true
      stdout: true

- shell:
    - [
        git submodule sync -- config/nvim && git submodule update -- config/nvim,
        Downloading submodule; daephx/nvim,
      ]

- link:
    ~/.config/nvim:
      path: config/nvim

- shell:
    - [
        sudo sh -c " \
        add-apt-repository -y ppa:neovim-ppa/unstable;
        apt update && apt install -y neovim",
        Downloading package; 'Neovim/Unstable',
      ]

- shell:
    - [
        sudo sh -c "\
        apt install -y ripgrep fd-find",
        Downloading external dependencies,
      ]

- shell:
    - [
        pip3 install neovim neovim-remote
        apt install -y ripgrep fd-find",
        Installing python compatabilities,
      ]

- shell:
    - [
        nvim --headless -c "autocmd User PackerComplete quitall",
        Installing plugins for 'NeoVim',
      ]
