# Install local themes

- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/.config/poshthemes/

- link:
    ~/.config/poshthemes:
      glob: true
      path: config/poshthemes/*
