# profile: Static/Dynamic user shell configuration

- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/.config/profile.d/

- clean:
    ~/: # Home directory
    ~/.config/profile.d:

- link:
    ~/.config/dir_colors: config/profile/dir_colors
    ~/.config/user-dirs.dirs: config/profile/user-dirs.dirs
    ~/.config/user-dirs.locale: config/profile/user-dirs.locale
    ~/.profile: config/profile/profile
    ~/.config/profile.d:
      force: true
      glob: true
      path: config/profile.d/*
