# GNU Readline: provides in-line editing and history for interactive programs

- create:
    - ~/.config/readline/

- clean:
    ~/.config/readline:

- link:
    ~/.config/readline/inputrc: config/readline/inputrc
