# Bourne Shell / common shell configurations

- defaults:
    link:
      force: true
      relink: true

- link:
    ~/.aliases: config/sh/aliases
    ~/.editor: config/sh/editor
    ~/.environment: config/sh/environment
    ~/.functions: config/sh/functions
    ~/.inputrc: config/sh/inputrc
    ~/.ls_colors: config/sh/ls_colors
    ~/.profile: config/sh/profile
    ~/.prompt: config/sh/prompt
