# Wezterm | A GPU-accelerated cross-platform terminal emulator and multiplexer
# https://github.com/wez/wezterm

- defaults:
    link:
      force: true
    shell:
      stderr: true
      stdout: true

- link:
    ~/.config/wezterm/: config/wezterm/

- shell:
    - [meta/scripts/install-wezterm.sh, "Running installation script: wezterm"]
