# zsh: zshell configuration

- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/.cache/zsh/
    - ~/.config/zsh/
    - ~/.local/share/zsh/
    - ~/.local/share/zsh/completion/
    - ~/.local/share/zsh/plugins/

- clean:
    ~/.config/zsh:
    ~/.local/share/zsh:

- link:
    ~/.zshenv: config/zsh/zshenv.zsh
    ~/.config/zsh/.zshenv: config/zsh/zshenv.zsh

    ~/.config/zsh/.zlogout: config/zsh/zlogout.zsh
    ~/.config/zsh/.zprofile: config/zsh/zprofile.zsh
    ~/.config/zsh/.zshrc: config/zsh/zshrc.zsh

    ~/.config/zsh/:
      glob: true
      path: config/zsh/*.zsh

    ~/.local/share/zsh/completion:
      glob: true
      path: config/zsh/completion/*

    ~/.local/share/zsh/plugins:
      glob: true
      path: config/zsh/plugins/*

- shell:
    - [
        "command -v zsh > /dev/null || sudo apt install -y zsh",
        "Installing package: zsh",
      ]
    - [
        "[ $SHELL = '/usr/bin/zsh' ] || sudo usermod -s $(which zsh) $USER",
        "Set zsh as default for $USER",
      ]
    - [
        sudo chmod -R 755 ~/.local/share/zsh/completion
        "Ensure executable permissions for custom zsh completions",
      ]
