# ZSH | Zshell configurations
- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/.config/zsh:

- link:
    ~/.zshenv: config/zsh/zshenv.zsh
    ~/.config/zsh/.zshrc: config/zsh/zshrc.zsh
    ~/.config/zsh/.zlogout: config/zsh/zlogout.zsh
    ~/.config/zsh/.zplugin: config/zsh/zplugin.zsh
    ~/.config/zsh/conf.d: config/zsh/conf.d

- shell:
    - [
        sh -c "if ! command -v zsh; then sudo apt install -y zsh; fi",
        Installing Package; 'zsh'
      ]
    - [
        sudo usermod -s $(which zsh) $USER,
        Set zsh as default for $USER
      ]
