- sudo:
    - shell:
        - [apt update && apt install -y zsh, Installing zsh.]

- shell:
    - [/usr/sbin/usermod -s $(which zsh) $USER, Set zsh as users default shell.]

- link:
    ~/.zshenv: dotfiles/zsh/.zshenv
    ~/.config/zsh/.zshrc: dotfiles/zsh/.zshrc
    ~/.config/zsh/.zshrc.d:
      glob: true
      path: dotfiles/zsh/.zshrc.d/*.zsh
    ~/.config/zsh:
      glob: true
      path: dotfiles/zsh/*
      exclude:
        [
          dotfiles/zsh/.zshenv,
          dotfiles/zsh/oh-my-zsh,
          dotfiles/zsh/z,
          dotfiles/zsh/zshrc,
          dotfiles/zsh/.zshrc.d,
        ]
