# zsh: zshell configuration

- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/.config/zsh/

- clean:
    ~/.config/zsh:

- link:
    ~/.zshenv: config/zsh/zshenv
    ~/.config/zsh/.zshrc: config/zsh/zshrc
    ~/.config/zsh/.zlogout: config/zsh/zlogout
    ~/.config/zsh/plugins: config/zsh/plugins

- shell:
    - [
        sh -c "if ! command -v zsh; then sudo apt install -y zsh; fi",
        Installing Package; 'zsh',
      ]
    - [sudo usermod -s $(which zsh) $USER, Set zsh as default for $USER]
