- create:
    - ~/.config/zsh

- link:
    ~/.zshenv: dotfiles/zsh/zshenv
    ~/.config/zsh/.zshrc: dotfiles/zsh/zshrc
    ~/.config/zsh:
      glob: true
      path: dotfiles/zsh/*
      exclude:
        - dotfiles/zsh/zshenv
        - dotfiles/zsh/zshrc

- sudo:
    - shell:
        - [apt update && apt install -y zsh, Installing zsh.]
        - [
            /usr/sbin/usermod -s $(which zsh) $USER,
            Set zsh as users default shell!,
          ]
