# ZSH | Zshell configurations
- create:
    - ~/.config/zsh

- link:
    ~/.zshenv: config/zsh/zshenv
    ~/.config/zsh/.zshrc: config/zsh/zshrc
    ~/.config/zsh:
      glob: true
      path: config/zsh/*

- shell:
    - [
        sh -c "if ! command -v zsh; then sudo apt install -y zsh; fi",
        Installing Package; 'zsh'
      ]
    - [
        sudo usermod -s $(which zsh) $USER,
        Set zsh as default for $USER
      ]
