# Specifies the network interface to use for the LocalIP readout
interface = "wlan0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = true

# Lengthen kernel output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Display the number of physical or logical cores of your processor.
physical_cores = false

# Display percentage next to memory usage
# memory_percentage = true

# Display percentage next to disk space usage
# disk_space_percentage = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
theme = "Neodymium"

# Displays only the specified readouts.
show = [
    "Host",
    "Machine",
    "Kernel",
    "Distribution",
    "OperatingSystem",
    "DesktopEnvironment",
    "WindowManager",
    "Resolution",
    "Backlight",
    "Packages",
    "LocalIP",
    "Terminal",
    "Shell",
    "Uptime",
    "Processor",
    "ProcessorLoad",
    "Memory",
    "Battery",
    # "GPU",
    # "DiskSpace",
]
