- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- create:
    - $HOME/.config

- clean:
    $HOME:
      force: true
    $HOME/.config:
      recursive: true

- shell:
    # -----------------------------------------------------------
    # Pre installation, install dependencies before setting environment variables
    # -----------------------------------------------------------
    - [sh scripts/pre-install.sh, Running pre installation script]

- link:
    # -----------------------------------------------------------
    # All the files we want to be linked into the home directory
    # -----------------------------------------------------------
    # SH
    ~/.aliases: src/sh/aliases
    ~/.profile: src/sh/profile

    # BASH
    ~/.bashrc: src/bash/bashrc
    ~/.bash_logout: src/bash/bash_logout

    # ZSH
    ~/.zshenv: src/zsh/.zshenv
    ~/.config/zsh/.zshrc: src/zsh/.zshrc
    ~/.config/zsh:
      glob: true
      path: src/zsh/*
      exclude: [src/zsh/zshrc, src/zsh/.zshenv, src/zsh/z, src/zsh/oh-my-zsh]
    ~/.config/zsh/.z: src/zsh/.z

    # Oh-my-zsh
    ~/.config/zsh/custom:
      path: src/zsh/custom
      force: true

    # Git
    ~/.config/git:
      glob: true
      force: true
      path: src/git/*

    # SSH
    ~/.ssh/config:
      path: src/ssh/config

    # Docker
    ~/.docker/config.json: src/docker/config.json

    # VIM
    ~/.config/vim/.vimrc: src/vim/.vimrc

- shell:
    # -----------------------------------------------------------
    # After all the variables are setup, we can run some more installation and update scripts
    # -----------------------------------------------------------

    - [
        ZSH="$HOME/.config/zsh/oh-my-zsh" sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended,
        Installing oh-my-zsh,
      ]
    - [mkdir -p ~/.config/oh-my-zsh/custom/, Creating 'oh-my-zsh' custom folder]
    - [
        mkdir -p ~/.config/oh-my-zsh/custom/plugins,
        Creating 'oh-my-zsh' custom plugins folder,
      ]
    - [git submodule update --init --recursive, Installing submodules]
