- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- create:
    - $HOME/.config

- clean:
    $HOME:
      force: true
    $HOME/.config:
      recursive: true

- shell:
    - [sh scripts/pre-install.sh, Running pre installation script]

- shell:
    - [git submodule update --init --recursive, Installing submodules]
