- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- create:
    - ~/.config

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- shell:
    - [sh scripts/pre-install.sh, Running pre installation script]
