- defaults:
    clean:
      force: true
    link:
      create: true
      force: true
      glob: true
      relink: true
    shell:
      stderr: true
      stdout: true

- create:
    - ~/.cache
    - ~/.config
    - ~/.local

- clean:
    ~/: # Home directory
    ~/.config:
      recursive: true

- shell:
    - [git submodule sync --recursive -- meta/dotbot]
    - [git submodule update --recursive -- meta/dotbot]
    - [sudo apt update, Updating package index]
