# base: default configuration applied before all dotbot commands.
# Manages creation and cleaning of XDG directories and synchronizing submodules.

- defaults:
    clean:
      force: true
    link:
      create: true
      force: true
      glob: true
      relink: true
    shell:
      stderr: true
      stdout: true

- create:
    # XDG Standard directories
    - $HOME/.cache/
    - $HOME/.config/
    - $HOME/.local/
    - $HOME/.local/share/
    - $HOME/.local/state/

    # Unsupported XDG directories
    - $HOME/.local/bin/
    - $HOME/.local/lib/
    - $HOME/.local/src/

- clean:
    $HOME/:

    # XDG Standard directories
    $HOME/.cache/:
    $HOME/.config/:
    $HOME/.local/share/:
    $HOME/.local/state/:

    # Unsupported XDG directories
    $HOME/.local/bin/:
    $HOME/.local/lib/:
    $HOME/.local/src/:

- shell:
    - [git submodule sync --recursive -- meta/dotbot]
    - [git submodule update --recursive -- meta/dotbot]
