- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true
    shell:
      stdout: true
      stderr: true

- create:
    - ~/.config
    - ~/.local
    - ~/.cache

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- shell:
    - git submodule sync --recursive
    - git submodule update --recursive
