#!/usr/bin/env bash
# ~/.bash_logout: executed by bash(1) when login shell exits.

cat <<-EOF
Thank you. Come again!
EOF

# when leaving the console clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
  [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
