# ~/.bashrc: executed by bash(1) for non-login shells.
# shellcheck shell=bash
# shellcheck disable=SC1090
# shellcheck disable=SC1091

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# XDG base directory specifications
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Set history file if not exists
export HISTFILE="$XDG_STATE_HOME/bash_history"

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s cmdhist
shopt -u lithist

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Dynamically source user configurations
for file in "$XDG_CONFIG_HOME"/profile.d/*.sh; do
  source "$file"
done
