#!/bin/env sh
#
#     █████╗ ██╗     ██╗ █████╗ ███████╗███████╗███████╗
#    ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#    ███████║██║     ██║███████║███████╗█████╗  ███████╗
#    ██╔══██║██║     ██║██╔══██║╚════██║██╔══╝  ╚════██║
# ██╗██║  ██║███████╗██║██║  ██║███████║███████╗███████║
# ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
# ~/.aliases: sourced commonrc, shorthand for shell cmds

# Easier navigation:
alias -- -="cd -"            # Previous directory
alias .....="cd ../../../.." # 4 Parents
alias ....="cd ../../.."     # 3 Parents
alias ...="cd ../.."         # 2 Parents
alias ..="cd .."             # 1 Parent
alias tmp="cd /tmp"          # System Temp
alias ~="cd ~"               # HOME `cd`|`~`

# Common mistakes
alias brwe="brew"   # Typos
alias where="which" # Dammit windows

# Exit mistakes
alias x='exit'
alias xa="exit"
alias Xa="exit"
alias xit="exit"
alias eexit="exit"
alias eit="exit"
alias exot="exit"
alias q='exit'
alias Q='exit'
alias \:q='exit'

# Editors
alias e="emacs"
alias v="$VISUAL"
alias vi="$VISUAL"

# Detect which `ls` flavor is in use
if ls --color >/dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
  eval 'dircolors $HOME/.ls_colors' >/dev/null
else # MacOS `ls`
  colorflag="-G"
  export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# Always use color output for `ls`
alias ls="command ls -lv --g ${colorflag}"
alias l="ls -CF"
alias la="ls -A"
alias ll="ls -alF"

# Use LSD as default || standard LS
if command -v lsd &>/dev/null; then
  alias ls="command lsd -l ${colorflag} "
  alias l="ls -l"
  alias la="ls -a"
  alias lla="ls -la"
  alias lt="ls --tree"
  alias tree="ls --tree"
fi

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias grep="grep --color=auto"

# Enable aliases to be sudo"ed
alias sudo="sudo "

# Recursively delete `.DS_Store` files
alias ds_cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple's System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# if apple
# Show/hide hidden files in Finder
# alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
# alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
# alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
# alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# fi # apple

# # Add an "alert" alias for long running commands.
# if command -v notify-send &>/dev/null; then
#    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# #   Example: sleep 10; alert
# fi

# Clear terminal output
alias cls="clear"
alias shell="ps -p $$"

# Reload the shell (i.e. invoke as a login shell)
alias reload="clear && exec $(sh -c 'ps -p $$ -o ppid=' | xargs -I'{}' readlink -f '/proc/{}/exe') -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'
# alias path2='echo $path tr ":" "\n"'

# Return the current public IP address
alias myip="curl http://ipecho.net/plain; echo"

# Make distructive commands interactive
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# View HTTP traffic | Requires ngrep
# alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
# alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\\: .*|GET \\/.*\""

# Trim new lines and copy to clipboard | Requires xclip
# alias c="tr -d '\\n' | xclip -selection clipboard"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
# alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
# alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
# alias afk="i3lock -c 000000"

# vhosts
alias hosts='sudo vim /etc/hosts'

# copy working directory | Requires xclip
# alias cwd='pwd | tr -d "\r\n" | xclip -selection clipboard | echo "=> Working Directory copied to pasteboard."'

# untar archive
alias untar='tar xvf'

# Pipe my public key to my clipboard. | Requires xclip
# alias pubkey="more ~/.ssh/id_ed25519.pub | xclip -selection clipboard | echo '=> Public key copied to pasteboard.'"

# Pipe my private key to my clipboard. | Requires xclip
# alias prikey="more ~/.ssh/id_ed25519 | xclip -selection clipboard | echo '=> Private key copied to pasteboard.'"

# human-readable sizes
alias df="df -h"

# Attempt to reclaim mem cache from WSL Guest
alias drop_cache="sudo sh -c \"echo 3 >'/proc/sys/vm/drop_caches' && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'\""
alias dps="docker ps | less -S"
alias ls-env="env | sed 's/;/\n/g'"

# Git aliases
# alias g="git"
# alias gc="git commit"
# alias gs="git status"
# alias gb="git branch"
# alias gs="git show"
