#!/usr/bin/env sh
# ~/.functions: Common functions for POSIX shells

# Extract archive formats
# Usage: extract <path/to/file>
function extract() {
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2) tar xjf $1 ;;
      *.tar.gz) tar xzf $1 ;;
      *.bz2) bunzip2 $1 ;;
      *.rar) unrar x $1 ;;
      *.gz) gunzip $1 ;;
      *.tar) tar xf $1 ;;
      *.tbz2) tar xjf $1 ;;
      *.tgz) tar xzf $1 ;;
      *.zip) unzip $1 ;;
      *.Z) uncompress $1 ;;
      *.7z) 7z x $1 ;;
      *.deb) ar x $1 ;;
      *.tar.xz) tar xf $1 ;;
      *.tar.zst) unzstd $1 ;;
      *) echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Get absolute path
# Usage: abspath <path/to/item>
function abspath() {
  pushd "$(dirname "$1")" >/dev/null
  printf "%s/%s\n" "$(pwd)" "$(basename "$1")"
  popd >/dev/null
}

# Create path on touch
# Usage: touchd <path/to/file>
function touchd() {
  mkdir -p "${1%/*}" && touch "$1"
}

# Source all files in directory
# Usage: source_files </dir/path/> bash
function source_files() {
  local dir="$1"
  local ext="$2"
  if [[ -d "$dir" && -r "$dir" && -x "$dir" ]]; then
    for file in "$dir"/*."$ext"; do
      [[ -f "$file" && -r "$file" ]] && . "$file"
    done
  fi
}

# Create and change directory
# Usage: mk </dir/path>
function mk() {
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}
