#!/usr/bin/env sh
#
#    ██╗███╗   ██╗██████╗ ██╗   ██╗████████╗██████╗  ██████╗
#    ██║████╗  ██║██╔══██╗██║   ██║╚══██╔══╝██╔══██╗██╔════╝
#    ██║██╔██╗ ██║██████╔╝██║   ██║   ██║   ██████╔╝██║
#    ██║██║╚██╗██║██╔═══╝ ██║   ██║   ██║   ██╔══██╗██║
# ██╗██║██║ ╚████║██║     ╚██████╔╝   ██║   ██║  ██║╚██████╗
# ╚═╝╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝    ╚═╝   ╚═╝  ╚═╝ ╚═════╝
# ~/.inputrc: user configuration file for GNU readline

# do not make noise
set bell-style none

# Make Tab autocomplete regardless of filename case
set completion-ignore-case on

# "\e":kill-whole-line
# Escape: unix-line-discard

# Use the text that has already been typed as the prefix for searching through
# commands (i.e. more intelligent Up/Down behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

# do history expansion when space entered
# Space: magic-space

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Use thetext that has already been typed as the prefix for searching through
# commands (i.e. more intelligent Up/Down behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

"\e[C": forward-char
"\e[D": backward-char

"\e[1;5C": forward-word   # ctrl + right
"\e[1;5D": backward-word  # ctrl + left

# "\e[1;2d": backward-word  # ctrl + left


# "\e":kill-whole-line
# Escape: unix-line-discard

# "\e[1;5C": forward-word
# "\e[1;5D": backward-word

# do history expansion when space entered
# Space: magic-space
