#!/usr/bin/env sh
#
#    ██╗███╗   ██╗██████╗ ██╗   ██╗████████╗██████╗  ██████╗
#    ██║████╗  ██║██╔══██╗██║   ██║╚══██╔══╝██╔══██╗██╔════╝
#    ██║██╔██╗ ██║██████╔╝██║   ██║   ██║   ██████╔╝██║
#    ██║██║╚██╗██║██╔═══╝ ██║   ██║   ██║   ██╔══██╗██║
# ██╗██║██║ ╚████║██║     ╚██████╔╝   ██║   ██║  ██║╚██████╗
# ╚═╝╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝    ╚═╝   ╚═╝  ╚═╝ ╚═════╝
# ~/.inputrc: user configuration file for GNU readline

# do not make noise
set bell-style none

# Make Tab autocomplete regardless of filename case
set completion-ignore-case on

# "\e":kill-whole-line
# Escape: unix-line-discard

# Use the text that has already been typed as the prefix for searching through
# commands (i.e. more intelligent Up/Down behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

# do history expansion when space entered
# Space: magic-space

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on
