#!/usr/bin/env zsh
#
#    ███████╗███████╗██╗  ██╗██████╗  ██████╗
#    ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
#      ███╔╝ ███████╗███████║██████╔╝██║
#     ███╔╝  ╚════██║██╔══██║██╔══██╗██║
# ██╗███████╗███████║██║  ██║██║  ██║╚██████╗
# ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
# ~/.zshrc: executed by zsh(1) for non-login shells.

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# profile loading timer init
integer t0=$(($(date +%s%N)/1000000))

# Set history file if not exists
export HISTFILE=${HISTFILE:-$XDG_STATE_HOME/zsh_history}

# ZSH Options
unsetopt BEEP


### User Configs ###

# Source common shell configurations
[ -f ~/.commonrc ] && source ~/.commonrc

# Zsh common source
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# ZSH config folder containing additional files to be sourced
source_files "$ZDOTDIR/zshrc.d" "zsh"


### Complete ###

# Output startup time
function {
  local -i t1 startup
  t1=$(($(date +%s%N)/1000000))
  startup=$(( t1 - t0 ))
  [[ $startup -gt 1 ]] && print "Loading shell profile took: ${startup}ms"
}
unset t0
