#!/bin/env sh
#
#     █████╗ ██╗     ██╗ █████╗ ███████╗███████╗███████╗
#    ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#    ███████║██║     ██║███████║███████╗█████╗  ███████╗
#    ██╔══██║██║     ██║██╔══██║╚════██║██╔══╝  ╚════██║
# ██╗██║  ██║███████╗██║██║  ██║███████║███████╗███████║
# ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
# ~/.aliases: sourced commonrc, shorthand for shell cmds

# shellcheck disable=1001

### System ###

# Easier navigation
alias -- -="cd -"            # Previous directory
alias .....="cd ../../../.." # 4 Parents
alias ....="cd ../../.."     # 3 Parents
alias ...="cd ../.."         # 2 Parents
alias ..="cd .."             # 1 Parent
alias ~="cd ~"               # HOME `cd`|`~`

alias tmp="cd /tmp"          # System Temp

# Common mistakes
alias brwe="brew"   # Type slower? NAY!
alias where="which" # Dammit windows

# Exit mistakes
alias x='exit'
alias xa="exit"
alias Xa="exit"
alias xit="exit"
alias eexit="exit"
alias eit="exit"
alias exot="exit"
alias q='exit'
alias Q='exit'
alias \:q='exit'

# Editors
alias e="emacs"
alias v="\$VISUAL"
alias vi="\$VISUAL"

# Clear terminal output
alias cls="clear"

# list mounted drives
alias mnt="mount | grep -E ^/dev | column -t | less"

# Output the current shell PID
alias shell="ps -p \$$"

# Enable sudo to expand aliases
alias sudo="sudo"

# Reload the shell (i.e. invoke as a login shell)
alias reload="clear && exec \$(sh -c 'ps -p \$$ -o ppid=' | xargs -I'{}' readlink -f '/proc/{}/exe') -l"

# Print each PATH entry on a separate line
alias path='echo -e "${PATH//:/\\n}" | less'

# Shorthand to display command history
alias hist="history"

# List environment
alias ls-env="env | sed 's/;/\n/g'"

### Utilities ###

# Detect which `ls` flavor is in use
if ls --color >/dev/null; then # GNU `ls`
  colorflag="--color=always"
  eval 'dircolors $HOME/.ls_colors' >/dev/null
else # MacOS `ls`
  colorflag="-G"
  export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

# Determine ls utility, Break loop on first found
# Priority determined left-right
set -- exa lsd ls
for ls in "$@"; do
  if command -v "$ls" >/dev/null; then
    break
  fi
done

# Apply utility specific overrides
case "$ls" in
  exa)
    alias ls="command exa \$colorflag -l --group-directories-first --icons"
    alias ll="ls -alF"
    alias la="ls -a"
    alias lt="ls --tree"
    alias tree="ls --tree"
    ;;
  lsd)
    alias ls="command lsd \$colorflag -l --group-directories-first"
    alias ll="ls -l"
    alias la="ls -a"
    alias lt="ls --tree"
    alias tree="ls --tree"
    ;;
  ls)
    alias ls="command ls \$colorflag -lv --g"
    alias l="ls -CF"
    alias la="ls -A"
    alias ll="ls -alF"
    ;;
esac

# Default to raw-control-characters
alias less="less -R"

# Always enable colored `grep` output
# NOTE: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# human-readable sizes
alias df="df -h"

# File size
alias fs="stat -f \"%z bytes\""

# un tar archive
alias untar='tar xvf'

# Recursively delete `.DS_Store` files
alias ds_cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Return the current public IP address
alias myip="curl http://ipecho.net/plain; echo"

# forgetful ifconfig
if ! command -v ifconfig >/dev/null; then
  alias ifconfig='ip -c a'
fi

# Git version control
if command -v git >/dev/null; then
  alias gti="git" # Misspelling
  alias g="git"   # Shorthand
  alias gc="git commit"
  alias gs="git status"
  alias gb="git branch"
  alias gs="git show"
fi

# Create gitignore file from online template
new_gitignore() {
  curl -sL "https://www.toptal.com/developers/gitignore/api/$*" >> .gitignore
}; alias ignore="new_gitignore"

# Docker container list
if command -v docker >/dev/null; then
  alias dps="docker ps | less -S"
fi

# Bat | Cat w/ wings
if command -v batcat >/dev/null; then
  alias bat="batcat"
fi

# If fd-find is installed
if command -v fdfind >/dev/null; then
  alias fd="fdfind"
fi

# Shorthand for python
alias py="/usr/bin/env python"
if command -v ipython >/dev/null; then
  alias ipy="ipython"
fi

# Python based syntax highlight like cat
if command -v pygmentize >/dev/null; then
  _pygmentize () {
    "pygmentize -l \$1 \$2 | less -R"
  }; alias pygmentize ="_pygmentize"
fi

# Xclip commands
if command -v xclip >/dev/null; then

  # copy working directory | Requires xclip
  alias cwd='pwd | tr -d "\r\n" | xclip -selection clipboard && echo "=> Working Directory copied to pasteboard."'

  # Pipe my public key to my clipboard. | Requires xclip
  alias public_key="less ~/.ssh/id_ed25519.pub | xclip -selection clipboard && echo '=> Public key copied to pasteboard.'"

  # Pipe my private key to my clipboard. | Requires xclip
  alias private_key="less ~/.ssh//id_rsa | xclip -selection clipboard && echo '=> Private key copied to pasteboard.'"
fi

# If WSL: Enable windows subsystem aliases
# Alternative check: attempting to avoid spawning grep
# read var </proc/version ; if echo $var == *wsl 1>/dev/null ; then echo wsl; fi
if grep -q '[Mm]icrosoft' /proc/version; then
  # quick sanity check
  alias is_wsl="echo 'true'"

  # Attempt to reclaim memory cache from WSL Guest
  alias drop_cache="sudo sh -c \
  \"echo 3 >'/proc/sys/vm/drop_caches' \
  && swapoff -a && swapon -a \
  && printf '\n%s\n' 'Ram-cache and Swap Cleared'\" \
  "
fi
