#!/usr/bin/env sh
#
#    ██╗   ██╗███████╗███████╗██████╗ ███████╗███╗   ██╗██╗   ██╗
#    ██║   ██║██╔════╝██╔════╝██╔══██╗██╔════╝████╗  ██║██║   ██║
#    ██║   ██║███████╗█████╗  ██████╔╝█████╗  ██╔██╗ ██║██║   ██║
#    ██║   ██║╚════██║██╔══╝  ██╔══██╗██╔══╝  ██║╚██╗██║╚██╗ ██╔╝
# ██╗╚██████╔╝███████║███████╗██║  ██║███████╗██║ ╚████║ ╚████╔╝
# ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝  ╚═══╝
# ~/.environment: initialize common user environment variables

# shellcheck disable=SC1091

# XDG base directory specifications
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Unofficial XDG, extended specifications
# These are not standardized but are useful and common
export XDG_BIN_HOME="$XDG_LOCAL_HOME/bin"
export XDG_LIB_HOME="$XDG_LOCAL_HOME/lib"

# Dotfiles locations
export DOTFILES="$HOME/.dotfiles"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# You may need to manually set your language environment
export LANG="en_US.UTF-8"

# Personal Additions
# export DISPLAY=:0.0
# export LIBGL_ALWAYS_INDIRECT=1

# History
# Configure how the history is written
export HISTSIZE=10000
export HISTFILESIZE=100000
export SAVEHIST=10000
export HISTCONTROL=ignoreboth
export HISTIGNORE='ls:ll:la:lc:lt:cd:gt:up:todo:exit:clear:cls:hist:history'

# Manpager
# Define how to display man pages
export MANPAGER="less -s -M +Gg"
# export MANPAGER="nvim +Man"
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Set less command properties
export LESS="$LESS -FIJMQRSWX -x4 -z4"
export LESSHISTFILE=-

# Set variables for coloring LESS output
LESS_TERMCAP_mb="$(printf '\e[01;31m')" # enter blinking mode - red
LESS_TERMCAP_md="$(printf '\e[01;34m')" # enter double-bright mode - bold, blue
LESS_TERMCAP_me="$(printf '\e[0m')" # turn off all appearance modes (mb, md, so, us)
LESS_TERMCAP_se="$(printf '\e[0m')" # leave standout mode
LESS_TERMCAP_so="$(printf '\e[01;33m')" # enter standout mode - yellow
LESS_TERMCAP_ue="$(printf '\e[0m')" # leave underline mode
LESS_TERMCAP_us="$(printf '\e[04;36m')" # enter underline mode - cyan

# Export LESS variables
export LESS_TERMCAP_mb
export LESS_TERMCAP_md
export LESS_TERMCAP_me
export LESS_TERMCAP_se
export LESS_TERMCAP_so
export LESS_TERMCAP_ue
export LESS_TERMCAP_us

# Doom emacs direct
export EMACSDIR="$XDG_CONFIG_HOME/emacs"
export DOOMDIR="$XDG_CONFIG_HOME/doom"
if [ -d "$EMACSDIR" ]; then
  export PATH="$PATH:${EMACSDIR}/bin"
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Python Settings
# Python startup file, basic repl customization.
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"

# Make python look in '~/.local/share/python/lib' for custom modules and packages
export PYTHONPATH="$PYTHONPATH:$XDG_LOCAL_HOME/share/python/lib"

# Lua Settings
# Trailing ;; ensure that default path will be appended by Lua
LUA_LIB="$XDG_LOCAL_HOME/lib/lua" # Custom module location
export LUA_PATH="$LUA_PATH;$LUA_LIB/?.lua;$LUA_LIB/?/init.lua;;"
export LUA_CPATH="$LUA_CPATH;$LUA_LIB/?.so;$LUA_LIB/?/init.so;;"
export LUAROCKS_CONFIG="$XDG_CONFIG_HOME/luarocks/config.lua"
unset LUA_LIB

# Go settings
export GOPATH="$XDG_LOCAL_HOME/lib/go"
export PATH="$PATH:$GOPATH/bin"

# WGet Settings
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
alias wget="wget --hsts-file $XDG_CACHE_HOME/wget/history"

# GnuPG
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

# Ripgrep Configuration
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"

## Default commands
export FZF_DEFAULT_COMMAND="rg -uu --files -H"
export FZF_ALT_COMMAND="fd -uu -t f"

## Default Movement
export FZF_MOVEMENT="\
  --bind='alt-a:toggle-all' \
  --bind='alt-d:page-down+refresh-preview' \
  --bind='alt-g:ignore' \
  --bind='alt-h:backward-char+refresh-preview' \
  --bind='alt-l:forward-char+refresh-preview' \
  --bind='alt-p:toggle-preview' \
  --bind='alt-s:toggle-sort' \
  --bind='alt-u:page-up+refresh-preview' \
  --bind='alt-y:yank' \
  --bind='ctrl-a:preview-page-up' \
  --bind='ctrl-d:half-page-down+refresh-preview' \
  --bind='ctrl-g:top' \
  --bind='ctrl-l:clear-screen'
  --bind='ctrl-s:preview-page-down' \
  --bind='ctrl-u:half-page-up+refresh-preview' \
  --bind='ctrl-y:kill-line' \
  --bind='esc:unix-line-discard'"

## Default options
export FZF_DEFAULT_OPTS="$FZF_MOVEMENT \
  --layout=reverse \
  --margin=0 \
  --pointer='❯' \
  --prompt='❯ ' \
  --color=dark \
  --color=bg+:0 \
  --color=bg:-0 \
  --color=fg+:15 \
  --color=fg:#808080 \
  --color=header:#EEFA00 \
  --color=hl+:3 \
  --color=hl:3 \
  --color=info:#D68EB2 \
  --color=marker:4 \
  --color=pointer:1 \
  --color=prompt:4 \
  --color=spinner:11"

## fzf - Use basic colors if display not set
if [[ -z "$DISPLAY" ]]; then
  FZF_DEFAULT_OPTS+="
    --color=info:1 \
    --color=prompt:2 \
    --color=pointer:3 \
    --color=hl+:4 \
    --color=marker:6 \
    --color=spinner:7 \
    --color=header:8 \
    --color=border:9 \
    --color=hl:122 \
    --color=preview-fg:11 \
    --color=fg:13 \
    --color=fg+:15"
fi

# Common shell sources
[ -f ~/.aliases ] && . "$HOME/.aliases"
[ -f ~/.editor ] && . "$HOME/.editor"
[ -f ~/.functions ] && . "$HOME/.functions"
[ -f ~/.prompt ] && . "$HOME/.prompt"

# Initialize TMUX Session
if [ -z "$TMUX" ] && command -v tmux >/dev/null; then
  (tmux attach -t default || tmux new -s default) && return || exit
fi
