# ~/.zshrc: executed by zsh(1) for non-login shells.
# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck shell=zsh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# profile loading timer init
integer t0=$(($(date +%s%N)/1000000))

# Set history file if not exists
HISTFILE="$XDG_STATE_HOME/zsh/history"


### Options ###

# Enable
setopt GLOB_COMPLETE # enable glob matching for competition
setopt HIST_APPEND # append new commands to histfile
setopt HIST_EXPIRE_DUPS_FIRST # delete dupes when histfile exceeds histsize
setopt HIST_FIND_NO_DUPS # don't display duplicates when searching histfile
setopt HIST_IGNORE_ALL_DUPS # overwrite duplicate commands in histfile
setopt HIST_IGNORE_DUPS # ignore duplicated commands history list
setopt HIST_IGNORE_SPACE # ignore commands that start with space
setopt HIST_SAVE_NO_DUPS # ignore duplicates when saving to histfile
setopt INTERACTIVE_COMMENTS # allow comments in interactive shells
setopt SHARE_HISTORY # append and imports commands from histfile

# Disable
unsetopt AUTO_REMOVE_SLASH # remove completed slash after delimiter character
unsetopt BEEP # turn off terminal bells
unsetopt EXTENDED_HISTORY # save command timestamps to histfile
unsetopt LIST_AMBIGUOUS
unsetopt MENU_COMPLETE # do not auto select the first completion entry


### Completions ###

autoload -Uz compinit
zmodload zsh/complist
compinit -d "$XDG_CACHE_HOME/zsh/zccompdump"
_comp_options+=(globdots) # Include hidden files.

### Styles ###

zle_highlight=('paste:none')

## case-insensitive (uppercase from lowercase) completion
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
## case-insensitive (all) completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
## case-insensitive,partial-word and then substring completion
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

zstyle ':completion:*' menu select
# zstyle ':completion::complete:lsof:*' menu yes select

# Tab completion colors
# zstyle ":completion:*:default" list-colors ${(s.:.)LS_COLORS} "ma=16;5;244;2"
zstyle ':completion:*:options' list-colors '=^(-- *)=34'

autoload -Uz colors && colors


### Bindings ###

stty start undef # Disable Ctrl-q closing terminal
stty stop undef # Disable Ctrl-s to freeze terminal

# Set Vim-like binding mode
bindkey -v

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

bindkey "\e" kill-whole-line

bindkey "^j" down-line-or-beginning-search # Down
bindkey "^k" up-line-or-beginning-search   # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^p" up-line-or-beginning-search   # Up

# Cycle through history based on characters already typed on the line
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "$key[Up]" up-line-or-beginning-search
bindkey "$key[Down]" down-line-or-beginning-search

### Source ###

# Dynamically source user configurations
for file in "$XDG_CONFIG_HOME"/profile.d/*.sh; do
  source "$file"
done

### Plugins ###

# Zap: a minimal zsh plugin manager
# https://github.com/zap-zsh/zap
ZAP_DIR="$XDG_DATA_HOME/zap"
[ -f "$ZAP_DIR/zap.zsh" ] && source "$ZAP_DIR/zap.zsh" || {
  git clone --depth 1 -b "master" "https://github.com/zap-zsh/zap.git" "$ZAP_DIR" > /dev/null 2>&1 || {
    echo "E: Failed to install Zap"
  }
}

# Initialize plugins
plug 'Aloxaf/fzf-tab'
plug 'MenkeTechnologies/zsh-dotnet-completion'
plug 'MichaelAquilina/zsh-autoswitch-virtualenv'
plug 'chitoku-k/fzf-zsh-completions'
plug 'jeffreytse/zsh-vi-mode'
plug 'zsh-users/zsh-autosuggestions'
plug 'zsh-users/zsh-completions'
plug 'zsh-users/zsh-syntax-highlighting'

# Output startup time
function {
  local -i t1 startup
  t1=$(($(date +%s%N)/1000000))
  startup=$(( t1 - t0 ))
  [[ $startup -gt 1 ]] && print "Loading shell profile took: ${startup}ms"
}
unset t0
