console_title_template = '{{if .Root}}root :: {{end}}{{.Shell}} :: {{.Folder}}'
version = 3
final_space = true

[secondary_prompt]
  template = ' ❯ '
  foreground = '8'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '▓'
    foreground = 'black'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{.Icon}} <8></>'
    foreground = '7'
    background = 'black'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      alpine = '<#0f5779></>'
      aosc = '<#fafafa></>'
      arch = '<#1b90c8></>'
      cache_duration = 'none'
      centos = '<#fafafa></>'
      coreos = '<#fafafa></>'
      debian = '<#d70a53></>'
      devuan = '<#fafafa></>'
      elementary = '<#526ec8></>'
      fedora = '<#52a5d8></>'
      gentoo = '<#918ccb></>'
      linux = '<#fafafa></>'
      macos = '<#fafafa></>'
      mageia = '<#425979></>'
      manjaro = '<#39b860></>'
      mint = '<#83b74d></>'
      nixos = '<#5075ba></>'
      opensuse = '<#71b337></>'
      raspbian = '<#bc1a48></>'
      sabayon = '<#fafafa></>'
      slackware = '<#556fb3></>'
      ubuntu = '<#E95420></>'
      windows = '<#26C6DA></>'

  [[blocks.segments]]
    template = '  <8></>'
    foreground = 'lightYellow'
    powerline_symbol = ''
    background = 'black'
    type = 'root'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      root_icon = ''

  [[blocks.segments]]
    template = ' {{.Path}}{{if not .Writable}} <1></>{{end}}'
    foreground = 'lightBlue'
    powerline_symbol = ''
    background = 'black'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '…'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '<8></> {{.UpstreamIcon}}{{.HEAD}}{{.BranchStatus}}{{if .Working.Changed}}  <red>{{.Working.String}}</>{{end}}{{if and (.Staging.Changed) (.Working.Changed)}} |{{end}}{{if .Staging.Changed}}  <lightGreen>{{.Staging.String}}</>{{end}}{{if gt .StashCount 0}}  {{.StashCount}}{{end}}{{if gt .WorktreeCount 0}}  {{.WorktreeCount}}{{end}} '
    foreground = 'yellow'
    powerline_symbol = ''
    background = 'black'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{if or (.Working.Changed) (.Staging.Changed)}}yellow{{end}}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{if gt .Ahead 0}}magenta{{end}}', '{{if gt .Behind 0}}cyan{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '  {{.Profile}}{{if .Region}}@{{.Region}}{{end}} <8></>'
    foreground = '214'
    powerline_symbol = ''
    background = 'black'
    type = 'aws'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' ﴃ {{.Name}} <8></>'
    foreground = '153'
    powerline_symbol = ''
    background = 'black'
    type = 'az'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'
      display_id = true
      display_name = true
      info_separator = ' @ '

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '214'
    powerline_symbol = ''
    background = 'black'
    type = 'azfunc'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '29'
    background = 'black'
    type = 'cmake'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{.Context}} <8></>'
    foreground = '26'
    background = 'black'
    type = 'docker'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{if .Error}}{{.Error}}{{else}}{{if .Version}} {{.Version}}{{end}} {{if .Name}}{{.Name}}{{end}}{{end}} <8></>'
    foreground = '227'
    background = 'black'
    type = 'project'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{.UnityVersion}}{{if .CSharpVersion}} {{.CSharpVersion}}{{end}} <8></>'
    foreground = '15'
    background = 'black'
    type = 'unity'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      http_timeout = 2000

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '25'
    powerline_symbol = ''
    background = 'black'
    type = 'dart'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Unsupported}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '69'
    powerline_symbol = ''
    background = 'black'
    type = 'dotnet'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '74'
    powerline_symbol = ''
    background = 'black'
    type = 'go'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '208'
    powerline_symbol = ''
    background = 'black'
    type = 'java'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '133'
    powerline_symbol = ''
    background = 'black'
    type = 'julia'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{.Full}} <8></>'
    foreground = '74'
    powerline_symbol = ''
    background = 'black'
    type = 'lua'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .PackageManagerIcon}}{{.PackageManagerIcon}} {{end}}{{.Full}} <8></>'
    foreground = '71'
    powerline_symbol = ''
    background = 'black'
    type = 'node'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '15'
    background = 'black'
    type = 'perl'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{if .Venv}}{{.Venv}} {{end}}{{.Full}}{{end}} <8></>'
    foreground = '214'
    powerline_symbol = ''
    background = 'black'
    type = 'python'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'context'
      folder_name_fallback = false

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '160'
    powerline_symbol = ''
    background = 'black'
    type = 'ruby'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{if .Error}}{{.Error}}{{else}}{{.Full}}{{end}} <8></>'
    foreground = '166'
    powerline_symbol = ''
    background = 'black'
    type = 'rust'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <6></> {{ .FormattedMs }} <8></>'
    foreground = '7'
    powerline_symbol = ''
    background = 'black'
    type = 'executiontime'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = '7'
    powerline_symbol = ''
    background = 'black'
    type = 'text'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{.Name}}'
    foreground = '7'
    background = 'black'
    type = 'shell'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '▓'
    foreground = 'black'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' ❯'
    foreground = '2'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}1{{end}}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
