# LazyGit: Custom user configuration
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  scrollPastBottom: true
  mainPanelSplitMode: "horizontal"
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - black
      - bold
    optionsTextColor:
      - default
    selectedLineBgColor:
      - bold
      - underline
    selectedRangeBgColor:
      - bold
      - underline
  showIcons: true
  showRandomTip: false
  authorColors:
    "*": default
    daephx: cyan
