# VSCode Wezterm Colors
# Style: vscode
[colors]
foreground = "#C7C7C7"
background = "#000000"
compose_cursor = "#2472C8"
cursor_bg = "#E5E510"
cursor_border = "#E5E510"
cursor_fg = "#000000"
selection_bg = "#274372"
ansi = [
    "#000000",
    "#CD3131",
    "#0DBC79",
    "#E5E510",
    "#2472C8",
    "#BC3FBC",
    "#11A8CD",
    "#E5E5E5",
]
bright = [
    "#666666",
    "#F14C4C",
    "#23D18B",
    "#F5F543",
    "#3B8EEA",
    "#D670D6",
    "#29B8DB",
    "#E5E5E5",
]

[colors.indexed]

[metadata]
name = "vscode"
origin_url = "https://github.com/Mofiqul/vscode.nvim/raw/main/extra/wezterm/vscode-dark.toml"
