#!/usr/bin/env bash
#
#    ██████╗  █████╗ ███████╗██╗  ██╗██████╗  ██████╗
#    ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔══██╗██╔════╝
#    ██████╔╝███████║███████╗███████║██████╔╝██║
#    ██╔══██╗██╔══██║╚════██║██╔══██║██╔══██╗██║
# ██╗██████╔╝██║  ██║███████║██║  ██║██║  ██║╚██████╗
# ╚═╝╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set history file if not exists
export HISTFILE=${HISTFILE:-$XDG_STATE_HOME/bash_history}

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s cmdhist
shopt -u lithist

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# Source common shell configurations
[ -f ~/.commonrc ] && source ~/.commonrc

# Bash common sources
[ -f ~/.bash_aliases ] && source ~/.bash_aliases

# bash config dir containing additional configs to be sourced
source_files "$XDG_CONFIG_HOME/bash/bashrc.d" "bash"
